### ISSUE TITLE
[Bug] 不支持LTSC2021

### ISSUE THREAD

**Issue by HangZhouXZH** [Lyxot/WSAOnWin10#41]
### Describe the bug

能安装程序，但无法启动系统，安装时有报错

### Steps to reproduce

1. 运行run.bat
2. 启动wsa
3. 在加载页面闪退

### Expected behaviour

正常启动

### Logs/Screenshots

Patching Windows 10 AppxManifest file...
使用“1”个参数调用“RemoveChild”时发生异常:“未将对象引用设置到对象的实例。”
                                                                                                                         部署操作进程: J:\用户文档\XZH\下载\WSA\WSA_2311.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon\AppxMa    Processing                                                                                                              [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo    ]                                                                                                                                  + FullyQualifiedErrorId : DotNetMethodException

使用“1”个参数调用“RemoveChild”时发生异常:“未将对象引用设置到对象的实例。”
所在位置 J:\用户文档\XZH\下载\WSA\WSA_2311.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon\Install.ps1
:181 字符: 5
+     $xml.Package.Extensions.RemoveChild($node) | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

### System (please complete the following information)

Version: [e.g. 21H2]
Build: [e.g. 19044.1288]
WSA Version: [e.g. 2311.40000.4.0]

### Additional context

![image](https://github.com/A-JiuA/WSAOnWin10/assets/102938713/038ef4f5-584d-4c90-9c35-d8b695e4d234)

https://github.com/A-JiuA/WSAOnWin10/assets/102938713/5544c7a1-fe55-469b-8db5-877e301cb19c

**Comment by A-JiuA** [comment]
低于19045.2311版本需要安装<a href="https://www.catalog.update.microsoft.com/Search.aspx?q=KB5014032" target="_blank" rel="noopener noreferrer">KB5014032</a> 及 <a href="https://www.catalog.update.microsoft.com/Search.aspx?q=KB5022834" target="_blank" rel="noopener noreferrer">KB5022834</a> 补丁

**Comment by A-JiuA** [comment]
另外建议不要放在含中文的路径下

**Comment by HangZhouXZH** [comment]
谢谢，成功运行了
